name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Pinging Database
        run: |
          curl -i -X GET "https://nivcbqduduqvjtdkotrt.supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
